### ISSUE TITLE
Persons without a personCode should not be processed

### ISSUE THREAD

**Issue by Rick-Jongbloed** [Tools4everBV/HelloID-Conn-Prov-Source-Raet-Beaufort-IAM-API#11]
Sometimes the API delivers incomplete records. We should not process these records.

**Comment by Rick-Jongbloed** [comment]
$persons  | ForEach-Object {
        # Sanitize dataset
        if ($_.personCode -eq $null) { continue }

**Comment by rschouten97** [comment]
Closed as duplicate of https://github.com/Tools4everBV/HelloID-Conn-Prov-Source-Raet-Beaufort-IAM-API/issues/8
